defaults:
  - meta: config.yaml
  - default_styling: config.yaml
  - _self_

version: 0.0.4
scene: 3D

slides:

  - title: Table of Contents
    number: "0.0"
    content:
      - type: items
        bullets:
          -         distance: 4
        anchor: "{{ title }}"



  - title:  
    number: "1.0"
    content:
      - type: items 
        bullets:
          -             - 
          - 
          -
          -
  - title :    
    number: "1.1"
    content:
      - type: text
        text: ""


