defaults:
  - meta: config.yaml
  - default_styling: config.yaml
  - _self_

version: 0.0.8

scene: 2D

slides:

#  - title: We'll look at...
#    number: "   "
#    content:
#      - type: items
#        bullets:
#          - "Introduction"
#          - "Traditional Organizational Structures"
#          - "Technological Disruptions"
#          - "Shifts in Management"
#          - "Evolution of Communication"
#          - "Cultural Shifts in Organizations"
#          - "Future Trends"
#          - "Challenges in Adapting to Technological Changes"
#          - "Conclusion"
#        distance: 3
#        anchor: "{{ title }}"
#

  - title: Introduction
    number: "1.0"
    content:
      - type: text
        text: "Organizations have undergone continuous change:"
        next_to:
          target: "{{ title }}"
          dir: 2*DOWN
        align_to:
          target: "{{ title }}"
          dir: LEFT
        weights:
          - text: "Organizations have undergone continuous change"
            weight: BOLD
        font_size: "self.s_size"
        no_next_slide: false
      - type: text 
        text: "Driven by evolving technologies, globalization, and workforce dynamics."
        next_to:
          target: "{{ last }}"
          dir:  DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"  
      - type: text
        text: "Objective: To explore the impact of technological disruptions on three key areas: "
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        weights:
          - text: "Objective"
            weight: BOLD
        font_size: "self.s_size"
        no_next_slide: false
      - type: items
        bullets:
          - Management Structures
          - Communication Processes
          - Organizational Culture
        distance: 1
        font_size: "self.vs_size"
        anchor: "{{ last }}"
      - type: text
        text: "• Why This Matters:"
        next_to:
          target: "{{ last }}"
          dir: 2*DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        weights:
          - text: "Why This Matters:"
            weight: BOLD
        font_size: "self.s_size"    
        no_next_slide: false
      - type: text
        text: "   ‣ Technology dictates how businesses operate, compete, and grow"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"   
        no_next_slide: false
      - type: text
        text: "   ‣ Understanding these changes is crucial for adapting to the future of work"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"  
  - title: Traditional Organizational Structures
    number: "2.0"
    content:
      - type: image
        image: Screenshot 2024-12-03 at 19-30-36 CEO.png
        scale: 0.6
        shift: RIGHT*3
        no_next_slide: false
      - type: text
        text: " •Management:"
        next_to:
          target: "{{ title }}"
          dir: 2*DOWN
        align_to:
          target: "{{ title }}"
          dir: LEFT
        weights:
          - text: "Management:"
            weight: BOLD
        font_size: "self.s_size"    
        no_next_slide: false
      - type: text
        text: " - Hierarchical and centralized."
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        no_next_slide: false
        font_size: "self.vs_size"
      - type: text
        text: " - Clear chain of command with authority concentrated at the top."
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"  
          
      - type: text
        text: " •Communication:"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ title }}"
          dir: LEFT
        weights:
          - text: "Communication"
            weight: BOLD
        font_size: "self.s_size"    
        no_next_slide: false
      - type: text
        text: " - Linear and top-down"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        no_next_slide: false
        font_size: "self.vs_size"
      - type: text
        text: " - Clear chain of command with authority concentrated at the top."
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"  

      - type: text
        text: " •Culture:"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ title }}"
          dir: LEFT
        weights:
          - text: "Culture"
            weight: BOLD
        font_size: "self.s_size"    
        no_next_slide: false
      - type: text
        text: " - Stability and predictability were prioritized over innovation."
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        no_next_slide: false
        font_size: "self.vs_size"
      - type: text
        text: " - Employee roles were rigid, with little room for autonomy or creativity."
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"

  - title: Technological Disruptions
    number: "3.0"
    content:
      - type: text
        text: "Technological advancements have disrupted traditional structures, leading to:"
        next_to:
          target: "{{ title }}"
          dir: DOWN*2
        align_to: 
          target: "{{ title }}"
          dir: LEFT
        font_size: "self.s_size"

      - type: text
        text: "01 : The Digital Revolution:"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to: 
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.s_size"
        weights:
           - text: "The Digital Revolution"
             weight: BOLD
        
      - type: text
        text: " • Introduction of personal computers, the internet, and cloud computing"
        next_to:
          target: "{{ last }}"
          dir: "{{ last }}"
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"  
            

      - type: text
        text: "02 : Globalization:"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to: 
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.s_size"
        weights:
           - text: "The Digital Revolution"
             weight: BOLD

          
      - type: text
        text: " • Technology enabled businesses to operate globally."
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size"  

      - type: text
        text: " 03 : Automation & Artificial Intelligence (AI):"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to: 
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.s_size"
        weights:
           - text: "The Digital Revolution"
             weight: BOLD

      - type: text
        text: " • Routine tasks automated, shifting focus to strategic roles"
        next_to:
          target: "{{ last }}"
          dir: DOWN
        align_to:
          target: "{{ last }}"
          dir: LEFT
        font_size: "self.vs_size" 

