defaults:
  - meta: config.yaml
  - default_styling: config.yaml
  - _self_

version: 0.0.4
scene: 3D

slides:

  - title: Table of Contents
    number: "0.0"
    content:
      - type: items
        bullets:
          - Cathode Ray Tube Experiment
        distance: 4
        anchor: "{{ title }}"

  - title: Cathode Ray Tube Experiment
    number: "1.0"
    hook:
      name: cathode-ray
      filename: hooks/cathode-ray.py
      functions: cathode_ray_step
      tube_color: BLUE_B
      bulb_color: GREEN
      default_opacity: 0.7
      material_colors:
        - ORANGE
        - GRAY
