title: "Black bodies spectrum"
footer:
  text: Preparatory Class 1, Chemistry 1
  bold:
    - Chemistry 1
author: Fadeli Ala Eddine, Remaidia Mouhammed Nadim 
time: Oct. 2024
logo:
  image: logoBlanc-300x262.png 
  scale: 1.0
base_url: https://alafadeli.github.io/presentation-cathode
thanks: "THANK YOU!"
