title: "Evolution of Organizational Structures"
footer:
  text: Preparatory Class 1, Human Engineering
author: G7B 
time: Dec. 2024
logo:
  image: logoBlanc-300x262.png 
  scale: 0.5
  shift: UP*2
base_url: https://alafadeli.github.io/presentation-cathode
thanks: "THANK YOU!"
