title: "Current projects overview"
footer:
  text: Preparatory Class 1 , Chemistry 
  bold:
    - Chemistry
author: Fadeli Ala Eddine
time: Sept. 2024
logo:
  image: logoBlanc-300x262.png 
  scale: 0.6
base_url:
thanks: "THANK YOU!"
